# =========================================================================
#   Ceedling - Test-Centered Build System for C
#   ThrowTheSwitch.org
#   Copyright (c) 2010-25 Mike Karlesky, Mark VanderVoord, & Greg Williams
#   SPDX-License-Identifier: MIT
# =========================================================================

:project:
  :which_ceedling: gem
  :ceedling_version: 1.0.1
  :use_mocks: TRUE
  :use_test_preprocessor: :none
  :use_deep_preprocessor: :none
  :use_backtrace: :simple
  :use_decorators: :auto
  :build_root: build
  :test_file_prefix: test_
  :default_tasks:
    - test:all
  :test_threads: 8
  :compile_threads: 8
  :release_build: FALSE

:mixins:
  :enabled: []
  :load_paths: []

:test_build:
  :use_assembly: FALSE

:release_build:
  :output: MyApp.out
  :use_assembly: FALSE
  :artifacts: []

:plugins:
  :load_paths: []
  :enabled:
    - module_generator
    - report_tests_pretty_stdout

:report_tests_log_factory:
  :reports:
    - json 
    - junit 
    - cppunit 
    - html 

:extension:
  :executable: .out

:paths:
  :test:
    - test/Common
    - test/support
  :source:
    - src/Common
    - /Users/mwesigwaguma/Desktop/repos/Projects/AdruinoProjects/arduino_stm32/build/vendor/unity/src # Add this line to include Unity source
  :include:
    - src/Common
    - /opt/homebrew/Cellar/avr-gcc@9/9.4.0_1/avr/include/
    - /Users/mwesigwaguma/Desktop/repos/Projects/AdruinoProjects/arduino_stm32/build/vendor/unity/src # Ensure this path is correct
  :support:
    - test/support
  :libraries: []

:files:
  :test:
    - test/Common/test_*.c
  :source:
    - src/Common/*.c
    - /Users/mwesigwaguma/Desktop/repos/Projects/AdruinoProjects/arduino_stm32/build/vendor/unity/src # Add this line to include Unity source file

:defines:
  :common: []
  :test:
    - TEST
  :release: []

:tools:
  :test_compiler:
    :executable: gcc
    :arguments:
      - -Wall
      - -Os
      - -I"src"
      - -I"src/Common"
      - -I"/Users/mwesigwaguma/Desktop/repos/Projects/AdruinoProjects/arduino_stm32/build/vendor/unity/src" # Ensure this path is correct
      - ${1} # Add this line to include the input file :test_linker:
    :executable: gcc
    :arguments:
      - -Wall
      - -Os
      - -I"src"
      - -I"src/Common"
      - -I"/Users/mwesigwaguma/Desktop/repos/Projects/AdruinoProjects/arduino_stm32/build/vendor/unity/src" # Ensure this path is correct
      - ${1} # Add this line to include the input file
  :test_linker:
    :executable: gcc
    :arguments:
      - -Wall
      - -Os
      - -I"src"
      - -I"src/Common"

:cmock:
  :plugins:
    - :ignore
    - :callback
  :verbosity: 2
  :when_no_prototypes: :warn
  :skeleton_path: ''
  :mock_prefix: 'mock_'
  :mock_suffix: ''
  :strippables: ['(?:__attribute__\s*\([ (]*.*?[ )]*\)+)']
  :attributes:
    - __ramfunc
    - __irq
    - __fiq
    - register
    - extern
  :c_calling_conventions:
    - __stdcall
    - __cdecl
    - __fastcall
  :treat_externs: :exclude
  :treat_inlines: :exclude
  :treat_as:
    uint8: HEX8
    uint16: HEX16
    uint32: UINT32
    int8: INT8
    bool: UINT8
  :memcmp_if_unknown: true
  :when_ptr: :compare_data
  :weak: ''
  :enforce_strict_ordering: true
  :fail_on_unexpected_calls: true
  :callback_include_count: true
  :callback_after_arg_check: false
  :exclude_setjmp_h: false

:unity:
  :defines:
    - UNITY_EXCLUDE_FLOAT

:environment: []